// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqvzfzynldzocvsmalta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxdnpmenlubGR6b2N2c21hbHRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NjAwNzQsImV4cCI6MjA3MDIzNjA3NH0.D_bpx8_tkzsG3nFl8ohDVynApvSeCB2ggyAan-72fP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});